{
 "title": "Opened to Merged",
 "tags": [
  "dashboard",
  "tikv",
  "active"
 ],
 "time": { "from": "now-1y", "to": "now-1w" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'opened_to_merged_docs_html'"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time from Open to Merge ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Median, 15th and 85th percentile of number of hours from open to merging for PR",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median & 85th percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"85th percentile time opened to merged (in hours)\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]p85'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time opened to merged (in hours)\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"15th percentile time opened to merged (in hours)\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]p15'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Time from open to merge ([[repogroup_name]], [[period]])",
   "type": "table-old",
   "description": "Time PRs from open to merge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"opened_to_merged_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]med'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"15th percentile\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]p15'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"85th percentile\"\nfrom\n  sopened_to_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge[[repogroup]]p85'\norder by\n  time"
    }
   ]
  },
  { "title": "Compare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Open to Merged Median Time  Compare ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Median percentile of the number of hours from open to merging for PR",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median & 85th percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]istopcontributingcompanymed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]nottopcontributingcompanymed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "The top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time from Open to Merged ([[repogroup_name]], [[period]])",
     "type": "graph",
     "description": "Median, 15th and 85th percentile of number of hours from open to merging for PR",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      {
       "format": "h",
       "label": "Opened to merged (median & 85th percentile)"
      }
     ],
     "targets": [
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"85th percentile time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]istopcontributingcompanyp85'\norder by\n  time"
      },
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]istopcontributingcompanymed'\norder by\n  time"
      },
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"15th percentile time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]istopcontributingcompanyp15'\norder by\n  time"
      }
     ]
    }
   ]
  },
  {
   "title": "Not top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time from Open to Merged ([[repogroup_name]], [[period]])",
     "type": "graph",
     "description": "Median, 15th and 85th percentile of number of hours from open to merging for PR",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      {
       "format": "h",
       "label": "Opened to merged (median & 85th percentile)"
      }
     ],
     "targets": [
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"85th percentile time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]nottopcontributingcompanyp85'\norder by\n  time"
      },
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]nottopcontributingcompanymed'\norder by\n  time"
      },
      {
       "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"15th percentile time opened to merged (in hours)\"\nfrom\n  spr_opened_to_merged_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_company[[repogroup]]nottopcontributingcompanyp15'\norder by\n  time"
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 }, "options": { "content": "${docs:raw}" } }
 ]
}