{
 "title": "PR Time Opened to Merged",
 "tags": [
  "dashboard",
  "chaosmesh",
  "active",
  "PRs"
 ],
 "time": { "from": "now-1y", "to": "now-1w" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "sig",
    "label": "SIG",
    "query": "select  sig_mentions_labels_name from tsig_mentions_labels_with_non order by 1"
   },
   {
    "name": "sig_value",
    "query": "select value  from (\n    (\n        select\n            sig_mentions_labels_value as value,\n            1 as ord\n        from\n             tsig_mentions_labels_with_non\n        where\n              sig_mentions_labels_name = '${sig:raw}'\n    )\n    union\n        select  'all' as value, 2 as ord\n) sub\norder by ord\nlimit 1"
   },
   {
    "name": "author_type",
    "label": "Author Type",
    "query": "From the top contributing company : topcontrib,From not top contributing company : othercompany,Bots : onlybots"
   }
  ]
 },
 "panels": [
  {
   "title": "PR Time opened to megred (${repogroup_name}, ${period}, ${sig} SIG)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"85th percentile time\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series =  'open2merge_sig${repogroup}${author_type:raw}${sig_value}p85'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}${author_type:raw}${sig_value}med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"15th percentile time\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}${author_type:raw}${sig_value}p15'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PR Time opened to merged (${repogroup_name}, ${period}, ${sig} SIG)",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"15th percentile\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}${author_type:raw}${sig_value}p15'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}${author_type:raw}${sig_value}med'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"85th percentile\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}${author_type:raw}${sig_value}p85'\norder by\n  time"
    }
   ]
  },
  {
   "title": "The median time compare with different author types ([[repogroup_name]], [[period]])",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"From the top contributing company\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}topcontrib${sig_value}med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"From not top contributing company\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}othercompany${sig_value}med'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"From Bots\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '${period}'\n  and series = 'open2merge_sig${repogroup}onlybots${sig_value}med'\norder by\n  time"
    }
   ]
  }
 ]
}