{
 "title": "Weekly Report",
 "tags": [
  "dashboard",
  "tidb",
  "active"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "period", "label": "Period", "query": "d,d7,w,m,q,y" },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   }
  ]
 },
 "panels": [
  { "title": "Opened and Merged PRs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PRs opened in PingCAP Org ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "PRs Opened" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tidb.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companyallexcludebotsistop'\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tidb.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companyallexcludebotsnottop'\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in PingCAP Org ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Merged PRs" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tidb.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companyallexcludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tidb.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companyallexcludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs opened in  TiDB Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "PRs Opened" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tidb.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytidbexcludebotsistop'\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tidb.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytidbexcludebotsnottop'\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in TIDB Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Merged PRs" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tidb.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytidbexcludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tidb.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytidbexcludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs opened in  TiKV Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "PRs Opened" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tikv.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytikvexcludebotsistop'\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tikv.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytikvexcludebotsnottop'\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in TiKV Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Merged PRs" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tikv.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytikvexcludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tikv.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytikvexcludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs opened in PD Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "PRs Opened" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tikv.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytikvpdexcludebotsistop'\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tikv.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companytikvpdexcludebotsnottop'\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in PD Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Merged PRs" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  tikv.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytikvpdexcludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  tikv.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companytikvpdexcludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs opened in  Chaos Mesh Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "PRs Opened" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  chaosmesh.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companychaosmeshexcludebotsistop'\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  chaosmesh.public.spr_opened_company\nwhere\n  $__timeFilter(time)\n  and series = 'pr_opened_companychaosmeshexcludebotsnottop'\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in Chaos Mesh Repo ([[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none", "label": "Merged PRs" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  chaosmesh.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companychaosmeshexcludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  chaosmesh.public.spr_merged_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_merged_companychaosmeshexcludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  { "title": "PR Open to Engagment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Median time of Not Top  Contributing Company ([[period]])",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "select\n  time,\n  value as \"PingCAP Org\"\nfrom\n  tidb.public.spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigallothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"TiDB Repo\"\nfrom\n  tidb.public.spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtidbothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"TiKV Repo\"\nfrom\n  tikv.public.spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtikvothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"PD Repo\"\nfrom\n  tikv.public.spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigpdothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Chaos Mesh Repo\"\nfrom\n  chaosmesh.public.spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigallothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Median time of (Not) Top  Contributing Company (PingCAP Org, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigalltopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigallothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Median time of (Not) Top  Contributing Company (TiDB Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtidbtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtidbothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Median time of (Not) Top  Contributing Company (TiKV Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtikvtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigtikvothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Median time of (Not) Top  Contributing Company (PD Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigpdtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigpdothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Median time of (Not) Top  Contributing Company (Chaos Mesh Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigchaosmeshtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not Top Contributing Company Median time\"\nfrom\n  spr_first_non_author_activity_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth_sigchaosmeshothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  { "title": "PR Open to Merge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Median time of Not Top  Contributing Company ([[period]])",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "select\n  time,\n  value as \"PingCAP Org\"\nfrom\n  tidb.public.spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigallothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"TiDB Repo\"\nfrom\n  tidb.public.spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtidbothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"TiKV Repo\"\nfrom\n  tikv.public.spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtikvothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"PD Repo\"\nfrom\n  tikv.public.spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigpdothercompanyallmed'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Chaos Mesh Repo\"\nfrom\n  chaosmesh.public.spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigchaosmeshothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Open to Merged Median Time  Compare (PingCAP Org, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of the top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigalltopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigallothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Open to Merged Median Time  Compare (TiDB Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of the top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtidbtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtidbothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Open to Merged Median Time  Compare (TiKV Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of the top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtikvtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigtikvothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Open to Merged Median Time  Compare (PD Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of the top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigpdtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigpdothercompanyallmed'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Open to Merged Median Time  Compare (Chaos Mesh Repo, [[period]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    {
     "format": "h",
     "label": "Opened to merged (median percentile)"
    }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of the top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigchaosmeshtopcontriballmed'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"opened_to_merged_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time of not top contributing company (in hours)\"\nfrom\n  spr_opened_to_merged_sig\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'open2merge_sigchaosmeshothercompanyallmed'\norder by\n  time"
    }
   ]
  }
 ]
}