{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $skipPGSecret := .Values.skipPGSecret -}}
{{ if not $skipPGSecret }}
# PG secret starts
{{- $pgAdminUser := or .Values.pgAdminUser (.Files.Get "secrets/PG_ADMIN_USER.secret") -}}
{{- $pgHost := or .Values.pgHost (.Files.Get "secrets/PG_HOST.secret") -}}
{{- $pgHostRO := or .Values.pgHostRO (.Files.Get "secrets/PG_HOST_RO.secret") -}}
{{- $pgPort := or .Values.pgPort (.Files.Get "secrets/PG_PORT.secret") -}}
{{- $pgPass := or .Values.pgPass (.Files.Get "secrets/PG_PASS.secret") -}}
{{- $pgPassRO := or .Values.pgPassRO (.Files.Get "secrets/PG_PASS_RO.secret") -}}
{{- $pgPassTeam := or .Values.pgPassTeam (.Files.Get "secrets/PG_PASS_TEAM.secret") -}}
{{ if and $pgAdminUser $pgHost $pgHostRO $pgPass $pgPassRO $pgPassTeam }}
---
apiVersion: v1
data:
  PG_ADMIN_USER.secret: {{ trim $pgAdminUser | b64enc }}
  PG_HOST.secret: {{ trim $pgHost | b64enc }}
  PG_HOST_RO.secret: {{ trim $pgHostRO | b64enc }}
  PG_PORT.secret: {{ trim $pgPort | b64enc }}
  PG_PASS.secret: {{ trim $pgPass | b64enc }}
  PG_PASS_RO.secret: {{ trim $pgPassRO | b64enc }}
  PG_PASS_TEAM.secret: {{ trim $pgPassTeam | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.pgSecret }}
  labels:
    name: devstats
    type: 'secret'
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_pg_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# PG secret ends
{{ end }}
{{- $skipGitHubSecret := .Values.skipGitHubSecret -}}
{{ if not $skipGitHubSecret }}
# GitHub secret starts
{{- $token := or .Values.githubOAuth (.Files.Get "secrets/GHA2DB_GITHUB_OAUTH.secret") -}}
{{ if $token }}
---
apiVersion: v1
data:
  GHA2DB_GITHUB_OAUTH.secret: {{ trim $token | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.oauthSecret }}
  labels:
    name: devstats
    type: 'secret'
type: {{ .Values.secretType }}
{{ else }}
missing_github_oauth_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# GitHub secret ends
{{ end }}
{{- $skipGrafanaSecret := .Values.skipGrafanaSecret -}}
{{ if not $skipGrafanaSecret }}
# Grafana secret starts
{{- $grafanaUser := or .Values.grafanaUser (.Files.Get "secrets/GF_SECURITY_ADMIN_USER.secret") -}}
{{- $grafanaPassword := or .Values.grafanaPassword (.Files.Get "secrets/GF_SECURITY_ADMIN_PASSWORD.secret") -}}
{{ if and $grafanaUser $grafanaPassword }}
---
apiVersion: v1
data:
  GF_SECURITY_ADMIN_USER.secret: {{ trim $grafanaUser | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD.secret: {{ trim $grafanaPassword | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.grafanaSecret }}
  labels:
    name: devstats
    type: 'secret'
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_grafana_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# Grafana secret ends
{{ end }}
{{ end }}
