{{- $skipIngress := .Values.skipIngress -}}
{{ if not $skipIngress }}
{{- $root := . -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devstats-ingress
  labels:
    name: devstats
    type: 'ingress'
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - api-{{ .Values.domainName }}
{{ range $index, $_ := .Values.projects }}
{{ if and (or (eq ($index|int) ($root.Values.indexIngressesFrom|int)) (gt ($index|int) ($root.Values.indexIngressesFrom|int))) (lt ($index|int) ($root.Values.indexIngressesTo|int)) }}
        - {{ .proj }}-{{ $root.Values.domainName }}
{{ end }}
{{ end }}
      secretName: devstats-tls
  rules:
    - host: api-{{ .Values.domainName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: devstats-api-server-service
              servicePort: 80
{{ range $index, $_ := .Values.projects }}
{{ if and (or (eq ($index|int) ($root.Values.indexIngressesFrom|int)) (gt ($index|int) ($root.Values.indexIngressesFrom|int))) (lt ($index|int) ($root.Values.indexIngressesTo|int)) }}
  - host: {{ .proj }}-{{ $root.Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: devstats-service-{{ .proj }}
          servicePort: 80
{{ end }}
{{ end }}
{{ end }}