[package]
name = "importer"
version = "0.1.0"
authors = ["hi-rustin <rustin.liu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }

[dependencies.crawler]
version = "~0.1.0"
path = "../crawler"