{
 "title": "Issues Age by Repository Group",
 "tags": [
  "dashboard",
  "pingcap",
  "issue",
  "active"
 ],
 "time": { "from": "now-1y", "to": "now-1w" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d,d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'issues_age_docs_html'"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current median time to close for issues created last [[period]] for repository group [[repogroup_name]]",
   "type": "singlestat",
   "description": "Current median closing time for recent issues.",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  descr\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Number of closed issues opened last [[period]] for repository group [[repogroup_name]]",
   "type": "singlestat",
   "description": "Number of closed issues opened recently",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time, value\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
   "type": "graph",
   "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "h", "label": "Median issue close time" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
   "type": "table-old",
   "description": "Median time to close and the number​ of issues created in [[repogroup]] repository group.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time"
    }
   ]
  },
  { "title": "Compare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
   "type": "graph",
   "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "h", "label": "Median issue close time" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time"
    }
   ]
  },
  {
   "title": "The top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current median time to close for issues created last [[period]] for repository group [[repogroup_name]]",
     "type": "singlestat",
     "description": "Current median closing time for recent issues.",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  descr\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number of closed issues opened last [[period]] for repository group [[repogroup_name]]",
     "type": "singlestat",
     "description": "Number of closed issues opened recently",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time, value\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]istopcontributingcompanyn'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
     "type": "graph",
     "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "h", "label": "Median issue close time" }
     ],
     "targets": [
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Average number of issues opened\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]istopcontributingcompanyn'\norder by\n  time"
      },
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median time to close issue\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time"
      }
     ]
    }
   ]
  },
  {
   "title": "Not top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current median time to close for issues created last [[period]] for repository group [[repogroup_name]]",
     "type": "singlestat",
     "description": "Current median closing time for recent issues.",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  descr\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number of closed issues opened last [[period]] for repository group [[repogroup_name]]",
     "type": "singlestat",
     "description": "Number of closed issues opened recently",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time, value\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]nottopcontributingcompanyn'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
     "type": "graph",
     "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "h", "label": "Median issue close time" }
     ],
     "targets": [
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Average number of issues opened\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]nottopcontributingcompanyn'\norder by\n  time"
      },
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median time to close issue\"\nfrom\n  sissue_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'issue_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time"
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 }, "options": { "content": "${docs:raw}" } }
 ]
}