---
projects:
  tidb:
    order: 1
    name: TiDB
    status: "-"
    command_line:
      - pingcap
    env:
      GHA2DB_EXCLUDE_REPOS:
        "pingcap/tikv,pingcap/pd,pingcap/pd-web,pingcap/chaos-mesh,\
         pingcap/ticdc-lib,pingcap/tidb-ansible,pingcap/tidb-helper,\
         pingcap/tidb-lightning,pingcap/tikv-client-lib-java,pingcap/etcdv3-gateway,\
         pingcap/tso,pingcap/mysqlrelay,pingcap/tidb-lmdb,pingcap/sqllogictest"
    psql_db: tidb
    main_repo: pingcap/tidb
    start_date: 2021-01-01T00:00:00Z
    join_date: null
    graduated_date: null
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  tikv:
    order: 2
    name: TiKV
    status: Graduated
    command_line:
      - "tikv,pingcap/tikv,pingcap/pd"
    start_date: 2020-01-01T00:00:00Z
    join_date: 2020-01-01T00:00:00Z
    graduated_date: 2020-09-02T00:00:00Z
    psql_db: tikv
    main_repo: tikv/tikv
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  chaosmesh:
    order: 3
    name: Chaos Mesh
    status: Sandbox
    command_line:
      - "chaos-mesh,pingcap/chaos-mesh"
    start_date: 2020-01-01T00:00:00Z
    join_date: 2020-01-01T00:00:00Z
    psql_db: chaosmesh
    main_repo: chaos-mesh/chaos-mesh
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  all:
    order: 255
    name: All Community
    status: "-"
    command_line:
      - "pingcap,tikv,chaos-mesh"
    start_date: 2014-01-01T00:00:00Z
    join_date: 2016-03-10T00:00:00Z
    psql_db: allprj
    main_repo: ''
    annotation_regexp: ''
    files_skip_pattern: ''
    project_scale: 5.0
    env:
      GHA2DB_EXCLUDE_REPOS:
        "pingcap/ticdc-lib,pingcap/tidb-ansible,pingcap/tidb-helper,\
         pingcap/tidb-lightning,pingcap/tikv-client-lib-java,pingcap/etcdv3-gateway,\
         pingcap/tso,pingcap/mysqlrelay,pingcap/tidb-lmdb,pingcap/sqllogictest"