{{- $skipIngress := .Values.skipIngress -}}
{{ if not $skipIngress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devstats-ingress
  labels:
    name: devstats
    type: 'ingress'
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- $root := . -}}
{{ range $index, $_ := .Values.projects }}
{{ if and (or (eq ($index|int) ($root.Values.indexIngressesFrom|int)) (gt ($index|int) ($root.Values.indexIngressesFrom|int))) (lt ($index|int) ($root.Values.indexIngressesTo|int)) }}
  - host: {{ .proj }}.{{ $root.Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: devstats-service-{{ .proj }}
          servicePort: 80
{{ end }}
{{ end }}
{{ end }}