{
 "title": "Contributor Profile",
 "tags": [
  "contributor",
  "chaosmesh",
  "dashboard",
  "repogroups",
  "active"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "Users",
    "query": "select users_name from tusers order by time asc"
   },
   { "name": "period", "label": "Period", "query": "d,7d,w,m,q,y" },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "Github Stats",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "![Github Stats](https://github-readme-stats.vercel.app/api?username=[[users]]&show_icons=true&theme=dark&hide_border=true)\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  license_prob\nFROM gha_repos\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Contributor Contributions In [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]contributions', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Contributor PRs In  [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]prs', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Contributor Activity In [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]activity', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Contributor Issues In [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]issues', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Contributor Commits In  [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]commits', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Developer Languages",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "options": {
    "content": "![Languages](https://github-readme-stats.vercel.app/api/top-langs/?layout=compact&username=[[users]]&show_icons=true&theme=dark&hide_border=true&hide_title=true)"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  license_prob\nFROM gha_repos\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Contributor Comments In [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]comments', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  },
  {
   "title": "Contributor Pushes In [[repogroup_name]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]pushes', '[^\\w]+',''))\norder by\n  time"
    }
   ]
  }
 ]
}