{
 "title": "Developer Activity Counts by Companies",
 "tags": [
  "dashboard",
  "repogroups",
  "table",
  "companies",
  "tikv",
  "active"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period_name",
    "label": "Range",
    "query": "select quick_ranges_name from tquick_ranges order by time"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "comments,commit_comments,commits,events,pushes,contributions,issue_comments,issues,prs,merged_prs,review_comments,active_repos"
   },
   {
    "name": "period",
    "query": "select quick_ranges_suffix from tquick_ranges where quick_ranges_name = '[[period_name]]'"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'developer_company_stats_docs_html'"
   },
   {
    "name": "country",
    "query": "select sub.value from (select country_value as value, 0 as ord from tcountries where country_name = '[[country_name]]' union select 'all', 1 as ord) sub order by sub.ord limit 1"
   },
   {
    "name": "country_name",
    "label": "Country",
    "query": "select 'All' union select country_name from tcountries order by 1"
   },
   {
    "name": "exclude_top_contribuing_company",
    "label": "Exclude the top contributing company",
    "query": "true,false"
   },
   {
    "name": "companies",
    "label": "Companies",
    "query": "select companies_name from tcompanies where\n ($exclude_top_contribuing_company=true and companies_name != 'PingCAP') or ($exclude_top_contribuing_company=false)"
   }
  ]
 },
 "panels": [
  {
   "title": "Developer with  [[metric]] Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n) sub"
    },
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n    and value > 1\n) sub"
    },
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n    and value > 4\n) sub"
    },
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n    and value > 8\n) sub"
    }
   ]
  },
  {
   "title": "Proportion of Contributors",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and (\n        split_part(name, '$$$', 2) = 'PingCAP'\n    )\n) sub"
    },
    {
     "rawSql": "select \n  count(distinct lower(split_part(sub.name, '$$$', 1)))\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and (\n        split_part(name, '$$$', 2) != 'PingCAP'\n    )\n) sub"
    }
   ]
  },
  {
   "title": "[[metric]]  Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum(sub.value)\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n) sub"
    }
   ]
  },
  {
   "title": "Proportion of Contributors’s [[metric]]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum(value)\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and  split_part(name, '$$$', 2) = 'PingCAP'\n) sub"
    },
    {
     "rawSql": "select \n  sum(value)\nfrom (\n  select\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and split_part(name, '$$$', 2) != 'PingCAP'\n) sub"
    }
   ]
  },
  {
   "title": "Developers statistics in [[full_name]]  Org ([[metric]], Range: [[period_name]], Repository group: [[repogroup_name]]), bots excluded",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"name\", \"value\" FROM \"developers_hist_[[metric]]_[[repogroup]]_[[period]]\" WHERE $timeFilter",
     "rawSql": "select \n  sub.\"Rank\",\n  split_part(sub.name, '$$$', 1) as name,\n  split_part(sub.name, '$$$', 2) as \"Company\",\n  sub.value\nfrom (\n  select row_number() over (order by value desc) as \"Rank\",\n    name,\n    value\n  from\n    shdev\n  where\n    series = 'hdev_[[metric]][[repogroup]][[country]]'\n    and period = '[[period]]'\n    and ('[[companies:csv]]' = 'null' or split_part(name, '$$$', 2) in ([[companies]]))\n    and (\n      '[[exclude_top_contribuing_company]]' = false\n      or ('[[exclude_top_contribuing_company]]' = true and split_part(name, '$$$', 2) != 'PingCAP')\n    )\n) sub"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 }, "options": { "content": "${docs:raw}" } }
 ]
}