{
 "title": "Open PR Age by Repository Group",
 "tags": [
  "dashboard",
  "tikv",
  "active"
 ],
 "time": { "from": "now-90d", "to": "now-1w" },
 "templating": {
  "list": [
   { "name": "period", "label": "Period", "query": "d,d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'prs_age_docs_html'"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current median age of opened PRs in [[repogroup_name]] repository group ([[period]])",
   "type": "singlestat",
   "description": "Current median age of opened PRs.",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  descr\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]m'\norder by\n  time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Current average number of opened PRs in [[repogroup_name]] repository group ([[period]])",
   "type": "singlestat",
   "description": "Current average number of opened PRs.",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time, value\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]n'\norder by\n  time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
   "type": "graph",
   "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "h", "label": "Median PRs age" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Average number of PRs opened\"\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]n'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median age of opened PRs\"\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]m'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
   "type": "table-old",
   "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median opened PRs age\"\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]m'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of opened PRs\"\nfrom\n  sprs_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'prs_age[[repogroup]]n'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Compare",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  },
  {
   "title": "Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
   "type": "graph",
   "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "h", "label": "Median PRs age" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"The top contributing company\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Not top contributing company\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time"
    }
   ]
  },
  {
   "title": "The top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current median age of opened PRs in [[repogroup_name]] repository group ([[period]])",
     "type": "singlestat",
     "description": "Current median age of opened PRs.",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 43 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  descr\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Current average number of opened PRs in [[repogroup_name]] repository group ([[period]])",
     "type": "singlestat",
     "description": "Current average number of opened PRs.",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 43 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time, value\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanyn'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
     "type": "graph",
     "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "h", "label": "Median PRs age" }
     ],
     "targets": [
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Average number of PRs opened\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanyn'\norder by\n  time"
      },
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median age of opened PRs\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time"
      }
     ]
    },
    {
     "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
     "type": "table-old",
     "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time as \"Time\",\n  descr as \"Median opened PRs age\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanym'\norder by\n  time"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of opened PRs\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]istopcontributingcompanyn'\norder by\n  time"
      }
     ]
    }
   ]
  },
  {
   "title": "Not top contributing company",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current median age of opened PRs in [[repogroup_name]] repository group ([[period]])",
     "type": "singlestat",
     "description": "Current median age of opened PRs.",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 44 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  descr\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Current average number of opened PRs in [[repogroup_name]] repository group ([[period]])",
     "type": "singlestat",
     "description": "Current average number of opened PRs.",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 44 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time, value\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanyn'\norder by\n  time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
     "type": "graph",
     "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "h", "label": "Median PRs age" }
     ],
     "targets": [
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Average number of PRs opened\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanyn'\norder by\n  time"
      },
      {
       "measurement": "reviewers_d",
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time,\n  value as \"Median age of opened PRs\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time"
      }
     ]
    },
    {
     "title": "Number/Age of Pull requests in [[repogroup_name]] repository group ([[period]])",
     "type": "table-old",
     "description": "Median age and number of pull requests created in [[repogroup]] repository group.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"descr\" FROM \"autogen\".\"prs_age_[[repogroup]]_median_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time as \"Time\",\n  descr as \"Median opened PRs age\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanym'\norder by\n  time"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"value\" FROM \"autogen\".\"prs_age_[[repogroup]]_number_[[period]][[aggregate]]\" WHERE $timeFilter",
       "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of opened PRs\"\nfrom\n  spr_age_company\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'pr_age_company[[repogroup]]nottopcontributingcompanyn'\norder by\n  time"
      }
     ]
    }
   ]
  },
  { "title": "Documention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 }, "options": { "content": "${docs:raw}" } }
 ]
}