FROM golang:1.16 AS builder

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates openssh-client git curl make
RUN go get -u github.com/rs/cors
RUN go get -u github.com/json-iterator/go
RUN mkdir -p /go/src/github.com/ti-community-infra/devstats

WORKDIR /go/src/github.com/ti-community-infra/devstats

ADD temp/devstatscode.tar .
ADD temp/grafana-tool-bins.tar .
ADD temp/devstats-config-cncf.tar .
ADD temp/devstats-config-shared.tar .
ADD temp/devstats-config-dev.tar .

RUN make docker_minimal_install

FROM alpine
RUN apk add git bash
COPY --from=builder /devstats-bins/* /usr/bin/
COPY --from=builder /etc/gha2db /etc/gha2db
