FROM nginx

EXPOSE 80

RUN apt update && apt install -y wget

COPY temp/*.svg /usr/share/nginx/html/
COPY temp/index_default.html /usr/share/nginx/html/index.html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY health/static_page_health_check.sh /usr/bin
