FROM alpine AS builder
WORKDIR /builder

ADD temp/devstats-api-bins.tar .
ADD temp/devstats-api-config-prod.tar .

FROM alpine
COPY --from=builder /builder/api /usr/bin/
COPY --from=builder /builder/projects.yaml /etc/gha2db/projects.yaml
CMD api
