---
columns:
  - table_regexp: '^scompany_activity$'
    tag: tcompanies
    column: companies_name
  - table_regexp: '^scountries'
    tag: tcountries
    column: country_name
  - table_regexp: '^(spr_stale_by_sig)'
    tag: tsig_mentions_labels_with_non
    column: sig_mentions_labels_name