affiliations: 'github_users.json'
bootstrapCommand: './devel/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
companyAcq: "companies.yaml"
concurrencyPolicy: Forbid
domainName: 'dev.devstats.tidb.io'
fullnameOverride: devstats
grafanaCommand: 'grafana_start.sh'
grafanaImage: 'miniantdev/devstats-grafana-dev:0.0.8'
grafanaMaxSurge: 1
grafanaMaxUnavailable: 1
grafanaNReplicas: 1
grafanaPodName: devstats-grafana
grafanaPort: 3000
grafanaRestartPolicy: Always
grafanaSecret: grafana-secret
imagePullPolicy: Always
indexCronsFrom: 0
indexCronsTo: 100
indexGrafanasFrom: 0
indexGrafanasTo: 100
indexIngressesFrom: 0
indexIngressesTo: 100
indexProvisionsFrom: 0
indexProvisionsTo: 100
indexPVsFrom: 0
indexPVsTo: 100
indexServicesFrom: 0
indexServicesTo: 100
limitsBootstrapCPU: '2000m'
limitsBootstrapMemory: '2Gi'
limitsCronsCPU: '6000m'
limitsCronsMemory: '16Gi'
limitsGrafanasCPU: '2000m'
limitsGrafanasMemory: '8Gi'
limitsPostgresCPU: '8000m'
limitsPostgresMemory: '16Gi'
limitsProvisionsCPU: '8000m'
limitsProvisionsMemory: '50Gi'
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
provisionImage: 'miniantdev/devstats-dev:0.0.8'
projectsFile: 'projects.yaml'
provisionCommand: './devel/deploy_all.sh'
provisionPodName: devstats-provision
provisionRestartPolicy: Never
postgresPort: 5432
postgresSvcName: 'devstats-postgres'
postgresImageName: 'lukaszgryglicki/devstats-patroni'
postgresStorageSize: '50Gi'
postgresNodes: 3
pvName: devstats-pvc
requestsBootstrapCPU: '200m'
requestsBootstrapMemory: '256Mi'
requestsCronsCPU: '1000m'
requestsCronsMemory: '2Gi'
requestsGrafanasCPU: '300m'
requestsGrafanasMemory: '512Mi'
requestsPostgresCPU: '2000m'
requestsPostgresMemory: '4Gi'
requestsProvisionsCPU: '1000m'
requestsProvisionsMemory: '2Gi'
secretType: Opaque
servicePodName: devstats-service
storageAccessModes: ReadWriteOnce
storageClass: gp2
skipTemp: 1
syncCommand: devstats
syncImage: 'miniantdev/devstats-minimal-dev:0.0.8'
syncPodName: devstats
syncRestartPolicy: Never
testsImage: 'miniantdev/devstats-dev:0.0.8'
testsPodName: devstats-tests
testsRestartPolicy: Never
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useFlags: ''
useBootstrapResourcesLimits: 1
useCronsResourcesLimits: 1
useGrafanasResourcesLimits: 1
useProvisionsResourcesLimits: 1
usePostgresResourcesLimits: 1
waitForBootstrap: 60
waitForPostgres: 15
projects:
  - proj: tidb
    db: tidb
    icon: 'tikv'
    org: 'PingCAP'
    repo: 'pingcap/tidb'
    cron: '10 * * * *'
    disk: 50Gi
    i: 0
  - proj: tikv
    db: tikv
    icon: 'tikv'
    org: 'TiKV'
    repo: 'tikv/tikv'
    cron: '30 * * * *'
    disk: 50Gi
    i: 1
  - proj: chaosmesh
    db: chaosmesh
    icon: 'tikv'
    org: 'Chaosmesh'
    repo: 'chaos-mesh/chaos-mesh'
    cron: '40 * * * *'
    disk: 50Gi
    i: 2
