---
projects:
  tidb:
    order: 1
    name: TiDB
    status: Graduated
    command_line:
      - tidb
    start_date: 2015-09-06T00:00:00Z
    join_date: 2015-09-06T00:00:00Z
    psql_db: tidb
    main_repo: pingcap/tidb
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  tikv:
    order: 2
    name: TiKV
    status: Graduated
    command_line:
      - tikv
    start_date: 2016-04-01T00:00:00Z
    join_date: 2018-08-28T00:00:00Z
    graduated_date: 2020-09-02T00:00:00Z
    psql_db: tikv
    main_repo: tikv/tikv
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  chaosmesh:
    order: 3
    name: Chaos Mesh
    status: Sandbox
    command_line:
      - chaos-mesh
    start_date: 2019-12-26T00:00:00Z
    join_date: 2020-07-14T00:00:00Z
    psql_db: chaosmesh
    main_repo: chaos-mesh/chaos-mesh
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'