---
projects:
  tidb:
    order: 1
    name: TiDB
    status: "-"
    command_line:
      - pingcap
    env:
      GHA2DB_EXCLUDE_REPOS:
        "pingcap/tikv,pingcap/pd,pingcap/pd-web,pingcap/chaos-mesh"
    psql_db: tidb
    main_repo: pingcap/tidb
    start_date: 2015-09-06T00:00:00Z
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  tikv:
    order: 2
    name: TiKV
    status: Graduated
    command_line:
      - "tikv,pingcap/tikv,pingcap/pd,pingcap/pd-web"
    psql_db: tikv
    main_repo: tikv/tikv
    start_date: 2016-04-01T00:00:00Z
    join_date: 2018-08-28T00:00:00Z
    graduated_date: 2020-09-02T00:00:00Z
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  chaosmesh:
    order: 3
    name: Chaos Mesh
    status: Sandbox
    command_line:
      - "chaos-mesh,pingcap/chaos-mesh"
    psql_db: chaosmesh
    main_repo: chaos-mesh/chaos-mesh
    start_date: 2019-12-26T00:00:00Z
    join_date: 2020-07-14T00:00:00Z
    project_scale: 5.0
    annotation_regexp: '^v\d+\.\d+\.\d+$'
    files_skip_pattern: '(^|/)_?(vendor|Godeps|_workspace)/'
  all:
    order: 4
    name: All Community
    status: "-"
    command_line:
      - "pingcap,tikv,chaos-mesh"
    psql_db: allprj
    main_repo: ''
    project_scale: 5.0
    start_date: 2015-09-06T00:00:00Z
    annotation_regexp: ''
    files_skip_pattern: ''
  ob:
    order: 5
    name: OceanBase
    status: "-"
    command_line:
      - "oceanbase"
    psql_db: ob
    main_repo: ''
    project_scale: 1
    start_date: 2021-05-31T00:00:00Z
    annotation_regexp: ''
    files_skip_pattern: ''
