{
 "title": "Contributor Profile",
 "tags": [
  "contributor",
  "tidb",
  "dashboard",
  "repogroups",
  "active"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "Users",
    "query": "select users_name from tusers order by time asc"
   },
   { "name": "period", "label": "Period", "query": "d,7d,w,m,q,y" },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "activity_type",
    "label": "Activity Type",
    "query": "Pull Request : pull_request, Issue : issue, Comment :  comment"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Github Stats",
     "type": "text",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
     "options": {
      "content": "<a href=\"https://github.com/${users}\" target=\"_blank\">![Github Stats](https://github-readme-stats.vercel.app/api?username=[[users]]&show_icons=true&theme=dark&hide_border=true)</a>\n"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  license_prob\nFROM gha_repos\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Contributor Contributions In [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]contributions', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Contributor PRs In  [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]prs', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Contributor Activity In [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]activity', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Contributor Issues In [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]issues', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Contributor Commits In  [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]commits', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Developer Languages",
     "type": "text",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
     "options": {
      "content": "![Languages](https://github-readme-stats.vercel.app/api/top-langs/?layout=compact&username=[[users]]&show_icons=true&theme=dark&hide_border=true&hide_title=true)"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  license_prob\nFROM gha_repos\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Contributor Comments In [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]comments', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    },
    {
     "title": "Contributor Pushes In [[repogroup_name]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select\n  time,\n  value\nfrom\n  sall_user_activity\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = lower(regexp_replace('user[[users]][[repogroup]]pushes', '[^\\w]+',''))\norder by\n  time"
      }
     ]
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 37, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "with prs_leatest as (\n  select\n      distinct id,\n      case when state = 'open' then 'open'\n           when state = 'closed' and (merged = true or merged_at IS NOT NULL)  then 'merged'\n           when state = 'closed' then 'closed'\n      end as status\n  from\n      gha_pull_requests pr\n  where\n      event_id in (select event_id from gha_pull_requests pr2 where pr2.event_id = pr.event_id order by updated_at limit 1)\n)\nselect\n  \"repoName\", \"number\", \"eventType\", \"title\", \"status\", \"commentId\", \"comment\", \"timestamp\", \"isPullRequest\"\nfrom \n(\n  -- PullRequestEvent\n  (\n    select\n        pr.dup_repo_name as \"repoName\",\n        pr.number as \"number\",\n        'pull_request_event_open_action' as \"eventType\",\n        pr.title as \"title\",\n        prl.status as \"status\",\n        0 as \"commentId\",\n        '' as \"comment\",\n        e.created_at as \"timestamp\",\n        true as \"isPullRequest\"\n    from\n        gha_events e,\n        gha_payloads p,\n        gha_pull_requests pr,\n        prs_leatest prl\n    where\n        'pull_request' in (${activity_type:singlequote})\n        and e.type = 'PullRequestEvent'\n        and e.dup_actor_login = '${users}'\n        and p.event_id = e.id\n        and p.action = 'opened'\n        and pr.event_id = e.id\n        and pr.id = prl.id\n        and e.created_at > $__timeFrom()\n        and e.created_at <= $__timeTo()\n  )\n  union\n  (\n    -- IssueEvent\n    select\n        i.dup_repo_name as \"repoName\",\n        i.number as \"number\",\n        'issue_event_open_action' as \"eventType\",\n        i.title as \"title\",\n        '-' as \"status\",\n        0 as \"commentId\",\n        '' as \"comment\",\n        e.created_at as \"timestamp\",\n        false as \"isPullRequest\"\n    from\n        gha_events e,\n        gha_payloads p,\n        gha_issues i\n    where\n        'issue' in (${activity_type:singlequote})\n        and e.type = 'IssueEvent'\n        and e.dup_actor_login = '${users}'\n        and p.event_id = e.id\n        and p.action = 'opened'\n        and i.event_id = e.id\n        and i.is_pull_request = false\n        and e.created_at > $__timeFrom()\n        and e.created_at <= $__timeTo()\n  )\n  union\n  (\n    -- Issue Comment Event\n    select\n        i.dup_repo_name \"repoName\",\n        i.number as \"number\",\n        'comment_event_create_action' as \"eventType\",\n        i.title as \"title\",\n        '-' as \"status\",\n        c.id as \"commentId\",\n        c.body as \"comment\",\n        e.created_at as \"timestamp\",\n        i.is_pull_request as \"isPullRequest\"\n    from\n        gha_events e,\n        gha_payloads p,\n        gha_issues i,\n        gha_comments c\n    where\n        'comment' in (${activity_type:singlequote})\n        and e.type in ('IssueCommentEvent', 'PullRequestReviewEvent', 'PullRequestReviewCommentEvent', 'CommitCommentEvent')\n        and e.dup_actor_login = '${users}'\n        and p.event_id = e.id\n        and i.event_id = e.id\n        and c.event_id = e.id\n        and e.created_at > $__timeFrom()\n        and e.created_at <= $__timeTo()\n  )\n) sub\norder by \"timestamp\" desc"
    }
   ]
  }
 ]
}