{
 "title": "Dashboards",
 "description": "Home dashboard",
 "tags": [
  "home",
  "all",
  "ob"
 ],
 "time": { "from": "now-7d", "to": "now-1h" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'dashboards_docs_html'"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "hostname",
    "query": "select value_s from gha_vars where name = 'os_hostname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Hourly [[full_name]] Project activity on GitHub",
   "type": "graph",
   "description": "Numbers of GitHub events in all repositories hourly",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Activity" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"events_h\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Number of GitHub events hourly\"\nfrom\n  sevents_h\nwhere\n  $__timeFilter(time)\norder by\n  time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Please report any bugs by opening an issue on <a href=\"https://github.com/ti-community-infra/devstats/issues\">ti-community-infra/devstats</a>.\n"
   }
  },
  {
   "title": "Active Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM stime_metrics\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Contributor Statistics Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PR Velocity Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Community Sizing and Health Assessment Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Issue Velocity Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Company Group Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Comment Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM sall_user_activity\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Other Dashboards", "type": "dashlist", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 } },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 }, "options": { "content": "${docs:raw}" } }
 ]
}