{
 "title": "PRs Closed in Repository Groups",
 "tags": [
  "dashboard",
  "ob",
  "active"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'prs_merged_docs_html'"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   }
  ]
 },
 "panels": [
  {
   "title": "PR closed (Not include merged PR)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PRs Closed ([[repogroup_name]], [[period]], Exclude Bots)",
   "type": "graph",
   "description": "The number of pull requests closed in [[repogroup]] repository group.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "none",
     "label": "Closed PRs (Not include merged PR)"
    }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"The top contribuing company\"\nfrom\n  spr_closed_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_closed_company[[repogroup_name]]excludebotsistop')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"Not top contribuing company\"\nfrom\n  spr_closed_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_closed_company[[repogroup_name]]excludebotsnottop')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs Closed in [[full_name]] repositories ([[period]])",
   "type": "graph",
   "description": "PRs closed in [[full_name]] repositories",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    {
     "format": "short",
     "label": "Closed PRs (Not include merged PR)"
    }
   ],
   "targets": [
    {
     "alias": "PRs merged",
     "measurement": "all_prs_merged_h",
     "query": "SELECT \"value\" FROM \"all_prs_merged_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"[[repogroup_name]] (excluding bots)\"\nfrom\n  spr_closed_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_closed_company[[repogroup_name]]excludebotsallcompany')\n  and period = '[[period]]'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time,\n  value as \"[[repogroup_name]] (including bots)\"\nfrom\n  spr_closed_company\nwhere\n  $__timeFilter(time)\n  and series = lower('pr_closed_company[[repogroup_name]]includebotsallcompany')\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  { "title": "PR closed or merged ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PRs Closed or Merged ([[repogroup_name]], [[period]], Exclude Bots)",
   "type": "graph",
   "description": "The number of pull requests closed or merged in [[repogroup]] repository group.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "PRs Closed or Merged" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  sub.time,\n  sum(sub.value) as \"The top contribuing company\"\nfrom (\n  (\n    select\n      time,\n      value\n    from\n      spr_closed_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_closed_company[[repogroup_name]]excludebotsistop')\n      and period = '[[period]]'\n  )\n  union\n  (\n    select\n      time,\n      value\n    from\n      spr_merged_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_merged_company[[repogroup_name]]excludebotsistop')\n      and period = '[[period]]'\n  )\n) sub\ngroup by time\norder by time"
    },
    {
     "measurement": "reviewers_d",
     "rawSql": "select\n  sub.time,\n  sum(sub.value) as \"Not top contribuing company\"\nfrom (\n  (\n    select\n      time,\n      value\n    from\n      spr_closed_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_closed_company[[repogroup_name]]excludebotsnottop')\n      and period = '[[period]]'\n  )\n  union\n  (\n    select\n      time,\n      value\n    from\n      spr_merged_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_merged_company[[repogroup_name]]excludebotsnottop')\n      and period = '[[period]]'\n  )\n) sub\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "PRs Closed or Merged  in [[full_name]] repositories ([[period]])",
   "type": "graph",
   "description": "PRs closed or merged in [[full_name]] repositories",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "PRs Closed or Merged" }
   ],
   "targets": [
    {
     "alias": "PRs merged",
     "measurement": "all_prs_merged_h",
     "query": "SELECT \"value\" FROM \"all_prs_merged_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  sub.time,\n  sum(sub.value) as \"[[repogroup_name]] (excluding bots)\"\nfrom (\n  (\n    select\n      time,\n      value\n    from\n      spr_closed_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_closed_company[[repogroup_name]]excludebotsallcompany')\n      and period = '[[period]]'\n  )\n  union\n  (\n    select\n      time,\n      value\n    from\n      spr_merged_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_merged_company[[repogroup_name]]excludebotsallcompany')\n      and period = '[[period]]'\n  )\n) sub\ngroup by time\norder by time"
    },
    {
     "rawSql": "select\n  sub.time,\n  sum(sub.value) as \"[[repogroup_name]] (includeing bots)\"\nfrom (\n  (\n    select\n      time,\n      value\n    from\n      spr_closed_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_closed_company[[repogroup_name]]includebotsallcompany')\n      and period = '[[period]]'\n  )\n  union\n  (\n    select\n      time,\n      value\n    from\n      spr_merged_company\n    where\n      $__timeFilter(time)\n      and series = lower('pr_merged_company[[repogroup_name]]includebotsallcompany')\n      and period = '[[period]]'\n  )\n) sub\ngroup by time\norder by time"
    }
   ]
  }
 ]
}