{
 "title": "Stale PRs by SIG",
 "description": "Stale PRs by SIG",
 "tags": [
  "dashboard",
  "SIGs",
  "PRs",
  "ob",
  "active"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sigs",
    "label": "SIG",
    "query": "select '\"' || sig_mentions_labels_name || '\"' from tsig_mentions_labels_with_non order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "Stale PRs by SIG (stale for 1 week or more)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  spr_stale_by_sig\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'pr_stale_by_sigw1'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Stale PRs by SIG (stale for 30 days or more)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  spr_stale_by_sig\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'pr_stale_by_sigd30'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Stale PRs by SIG (stale for 90 days or more)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  spr_stale_by_sig\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'pr_stale_by_sigd90'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "### Stale PRs by SIG\n\n- The metrics will only calculate the PR created within one year, and the PR created before more than one year will be ignored\n\n- The events of `PullRequestEvent` / `PullRequestReviewEvent` / `PullRequestReviewCommentEvent` / `IssueEvent`  / `IssueCommentEvent` happened on PR are considered as response, and the period from the last response time to the current time is regarded as the stale time\n\n- The number of PR whose stale time was more than 7 days, 30 days and 90 days was counted by SIG\n\n         "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"China\"\nFROM scountries\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}